apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heatshield.fullname" . }}-config
  labels:
    {{- include "heatshield.labels" . | nindent 4 }}
data:
  redis-url: {{ .Values.config.redisUrl | quote }}
  api-url: {{ .Values.config.apiUrl | quote }}
  model-path: {{ .Values.config.modelPath | quote }}
  batch-size: {{ .Values.config.batchSize | quote }}
