apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heatshield.fullname" . }}-secrets
  labels:
    {{- include "heatshield.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  bhuvan-api-key: {{ .Values.secrets.bhuvanApiKey | quote }}
